name: CDK DEPLOY

on:
  workflow_dispatch:

jobs:
  synth-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}
      # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: npm install
      run: npm install

    - name: Cdk Deploy
      run: npm run deploy
      env:
        CDK_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
        CDK_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
